name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Python settings
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest -v
